### ISSUE TITLE
Issue with Bot Template

### ISSUE THREAD

**Issue by sarthakjainxyz** [EnArvy/Discord-Gemini-Chatbot#1]
I made a Bot Template but it doesn't seem to work for me. My code:

bot_template = [
	{'role':'user','parts': ["who are you"]},
	{'role':'model','parts': ["Hello! I am a AI ChatBot! I am here to Provide you Support with all your issues! "]},
	{'role':'user','parts': ["can I get some info"]},
	{'role':'model','parts': ["Sure, here are some links : https://ThunderDevelops.in/ , https://host.thunderdevelops.in/minecraft-plans and https://panel.thunderdevelops.in/"]},
]

When I ask him who are you it sends the default message instead of this

**Comment by sarthakjainxyz** [comment]
I wanna add Context in it like in VertexAI where you can give the AI some knowledge about ur Server and his purpose. Example of my Context of VertexAI

``context="""You are Support assistant of Thunder Develops Company.
Thunder Develops is providing service like minecraft hosting, discord bot hosting & web service.
Panel Link: https://panel.thunderdevelops.in
Website: https://www.thunderdevelops.in
client often ask you questions about minecraft server development.""",
    )``

**Comment by EnArvy** [comment]
Works as intended, try to be more precise!
![Screenshot 2024-01-14 215919](https://github.com/EnArvy/Discord-Gemini-Chatbot/assets/70991883/c248e03e-a0ae-4670-8291-0a59a0329fe1)
