### ISSUE TITLE
Thread Feature

### ISSUE THREAD

**Issue by Murat1Na** [EnArvy/Discord-Gemini-Chatbot#4]
Hello i just have suggestion, there's a way to make the bot able to create thread and reply to all messages there, that will be really useful and nice

**Comment by EnArvy** [comment]
I can do it, but I really don't see the utility, can't you create a thread manually and use it?

**Comment by Murat1Na** [comment]
but the bot wont reply to all messages without mention or reply, just any way that the bot replyall messages like setup channel or thread or any way

like the idea of it when the bot create his own thread or we choose channel to setup the bot replies to all messages there

**Comment by EnArvy** [comment]
So what do you suggest? Something like `/createthread threadname:` ?

**Comment by Murat1Na** [comment]
yess great can be that

**Comment by EnArvy** [comment]
Sure I'll do it. As always, all data (including tracked threads) will be lost after bot restart. I plan to implement some form of database in the future if really needed, but not today. 
Maybe I can include a list of tracked channels in `config.py`. We'll see how it goes.

**Comment by EnArvy** [comment]
Implemented in 6cb61d3 .
Marking this as closed, please reopen if any bugs occur, haven't tested well.
