### ISSUE TITLE
How attach file pdf or mp3 to gemini on discord?

### ISSUE THREAD

**Issue by nghiencuuthuoc** [EnArvy/Discord-Gemini-Chatbot#8]
Hi Sir
Help me How attach file pdf or mp3 to gemini on discord?

![image](https://github.com/user-attachments/assets/5d61d9fc-41b8-4196-90bc-2343c1242b96)

**Comment by EnArvy** [comment]
Hi!

I am currently busy with life so making improvements you need will take some time. Meanwhile you can maybe try getting chatgpt or something to get the code modified as you need! You can add the docs as context from ai.google.dev/gemini-api/docs/ and create a pull request if you succeed.

**Comment by EnArvy** [comment]
@nghiencuuthuoc added support for docs and audio, but seems to be buggy. There are also limits on the input size. Closing this issue, please reopen if anything arises further.
